# Generated by Django 2.2.4 on 2025-11-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='date',
            new_name='sess_date',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='time',
            new_name='sess_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='users_attending',
        ),
        migrations.AddField(
            model_name='session',
            name='attendees',
            field=models.ManyToManyField(related_name='user_attendings_sessions', to='my_app.User'),
        ),
        migrations.AddField(
            model_name='session',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_sessions', to='my_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='meet_link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
