# Generated by Django 4.2.30 on 2026-06-11 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_pomodorohistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
